// AUTOGENERATED FILE -- DO NOT EDIT DIRECTLY
// See scripts/embed-mupdf.ts. Source installs resolve the package lazily.
export const embeddedMuPdfWasm: string | undefined = undefined;
export const embeddedMuPdfModule: string | undefined = undefined;
