import { describe, expect, test } from "bun:test";
import * as path from "node:path";
import { buildDocsIndexOutput } from "./check-public-version-sync";
import { findExaMcpDocFindings, parseEmbeddedDocs } from "./verify-g002-gates";

const generatedPath = "packages/coding-agent/src/internal-urls/docs-index.generated.ts";
const sourcePaths = ["README.md", "docs/tools/web_search.md", "docs/environment-variables.md"];
const embeddedKeys = ["README.md", "tools/web_search.md", "environment-variables.md"];
const cleanDocs = {
	"tools/web_search.md": "Exa requires EXA_API_KEY.",
	"environment-variables.md": "EXA_API_KEY enables Exa search.",
};

function corpus(docs: Record<string, string> = cleanDocs): string {
	return [
		"// Auto-generated by scripts/generate-docs-index.ts - DO NOT EDIT",
		'Reflect.set(globalThis, Symbol.for("gjc.docs-index.generated.loaded"), true);',
		"",
		`export const EMBEDDED_DOC_FILENAMES: readonly string[] = ${JSON.stringify(Object.keys(docs))};`,
		"",
		"export const EMBEDDED_DOCS: Readonly<Record<string, string>> = {",
		...Object.entries(docs).map(([key, content]) => `\t${JSON.stringify(key)}: ${JSON.stringify(content)},`),
		"};",
		"",
	].join("\n");
}

function findings(generated = corpus(), sources: Record<string, string> = {}): Promise<string[]> {
	return findExaMcpDocFindings(async file => {
		if (file === generatedPath) return generated;
		if (!sourcePaths.includes(file)) throw new Error(`unexpected source: ${file}`);
		return sources[file] ?? "Exa requires EXA_API_KEY.";
	});
}

describe("Exa MCP documentation scope", () => {
	test("allows the actual unrelated standalone MCP negative statements", async () => {
		const standalone = [
			"be refreshed by the runtime, but there is no public MCP OAuth authorization or",
			"reauthorization entry path, nor a public `/mcp` reconnection or reload contract.",
			"There is no public MCP config reload while the session runs; edit the config and start a new session. There is no subagent inheritance of exact-file tools beyond the parent session's exposed catalog.",
		].join("\n");
		expect(await findings(corpus({ ...cleanDocs, "standalone-mcp.md": standalone }))).toEqual([]);
	});

	for (const phrase of [
		"Exa MCP", "web_search_exa", "mcp.exa.ai", "without EXA_API_KEY", "falls to MCP",
		"fall back to MCP", "public MCP", "(or mcp)", "Exa search provider and Exa MCP",
	]) {
		for (const file of sourcePaths) {
			test(`rejects ${phrase} in source ${file}`, async () => {
				expect((await findings(corpus(), { [file]: `Exa search uses ${phrase}.` })).some(finding => finding.startsWith(`${file}:`))).toBe(true);
			});
		}
		for (const key of embeddedKeys) {
			test(`rejects ${phrase} in embedded ${key}`, async () => {
				const docs = { ...cleanDocs, [key]: `Exa search uses ${phrase}.` };
				expect((await findings(corpus(docs))).some(finding => finding.startsWith(`${generatedPath}#${key}:`))).toBe(true);
			});
		}
	}

	test("decodes JSON escapes before inspecting embedded policy text", async () => {
		const source = corpus({ ...cleanDocs, "tools/web_search.md": "public MCP" }).replace('"public MCP"', '"public \\u004dCP"');
		expect(await findings(source)).toContain(`${generatedPath}#tools/web_search.md: public MCP`);
	});

	test("round-trips quotes, backslashes, newlines and source-like text without evaluating it", () => {
		const content = '"quoted" \\ path\n};\nexport const EMBEDDED_DOCS = {};\n${throw new Error("executed")}';
		expect(parseEmbeddedDocs(corpus({ ...cleanDocs, "other.md": content })).get("other.md")).toBe(content);
	});

	test("parses the repository corpus using the existing generator format", async () => {
		const root = path.join(import.meta.dir, "..");
		const generated = await buildDocsIndexOutput(root);
		const docs = parseEmbeddedDocs(generated);
		for (const key of ["tools/web_search.md", "environment-variables.md", "standalone-mcp.md"]) {
			expect(docs.get(key)).toBe(await Bun.file(path.join(root, "docs", key)).text());
		}
		expect(await findings(generated)).toEqual([]);
	});
});

describe("malformed embedded corpus fails closed", () => {
	const valid = corpus();
	const malformed = {
		"missing source": "",
		"missing declaration": valid.replace("export const EMBEDDED_DOCS", "const OTHER_DOCS"),
		"truncated source": valid.slice(0, -4),
		"non-string value": valid.replace('"Exa requires EXA_API_KEY."', "null"),
		"invalid JSON escape": valid.replace('"Exa requires EXA_API_KEY."', '"\\x45xa"'),
		"executable value": valid.replace('"Exa requires EXA_API_KEY."', '(() => { throw new Error("executed"); })()'),
		"extra executable statement": `${valid}throw new Error("executed");\n`,
		"duplicate key": valid.replace("\n};", '\n\t"tools/web_search.md": "public MCP",\n};'),
		"filename mismatch": valid.replace('["tools/web_search.md","environment-variables.md"]', '["other.md"]'),
		"invalid filename type": valid.replace('["tools/web_search.md","environment-variables.md"]', '[1]'),
	};
	for (const [name, source] of Object.entries(malformed)) {
		test(name, async () => {
			expect(() => parseEmbeddedDocs(source)).toThrow();
			expect((await findings(source)).some(finding => finding.includes("invalid corpus"))).toBe(true);
		});
	}
	for (const key of ["tools/web_search.md", "environment-variables.md"]) {
		test(`missing required ${key}`, async () => {
			const docs: Record<string, string> = { ...cleanDocs };
			delete docs[key];
			expect(await findings(corpus(docs))).toContain(`${generatedPath}: missing embedded doc ${key}`);
		});
	}
	test("unreadable generated source produces a failing finding", async () => {
		const result = await findExaMcpDocFindings(async file => {
			if (file === generatedPath) throw new Error("unreadable");
			return "Exa requires EXA_API_KEY.";
		});
		expect(result).toContain(`${generatedPath}: invalid corpus (unreadable)`);
	});
});
